// Mood_Selector.java : Defines the mood selector for the java application.
// AI Puzzle: Level based of player's mood
// Gameplay features: Collision Detection, AI based level 
// Author: Shweta Patil
// Copyright: Shweta Patil © 2018

package Mood_Puzzle;

/**
 *
 * @author Shweta
 */

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

public class Mood_Selector extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Mood_Selector() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Question_Label = new javax.swing.JLabel();
        Emotion_Choser = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Question_Label.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Question_Label.setForeground(new java.awt.Color(255, 0, 0));
        Question_Label.setText("How are you feeling???");

        Emotion_Choser.setBackground(new java.awt.Color(255, 255, 255));
        Emotion_Choser.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        Emotion_Choser.setForeground(new java.awt.Color(255, 0, 0));
        Emotion_Choser.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mood", "Happy", "Sad", "Frustrated", "Overwhelmed", "Dull", "Excited", "Depressed", "Clound9" }));
        Emotion_Choser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Emotion_ChoserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(Emotion_Choser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(Question_Label)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(Question_Label)
                .addGap(27, 27, 27)
                .addComponent(Emotion_Choser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Emotion_ChoserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Emotion_ChoserActionPerformed
        String level;
        if(Emotion_Choser.getSelectedItem() == "Happy" || 
        Emotion_Choser.getSelectedItem() == "Sad" || 
        Emotion_Choser.getSelectedItem() == "Dull" || 
        Emotion_Choser.getSelectedItem() == "Excited") //Happy Sad Dull Excited
        { 
           level = "medium";
           Medium_Level.main(null);
           this.setVisible(false);
        }
        else if(Emotion_Choser.getSelectedItem() == "Frustrated" || 
        Emotion_Choser.getSelectedItem() == "Depressed") //Frustrated Depressed
        {
            level = "easy"; //Easy.setVisible(True);
            System.out.println("Push button working...");
            Easy_Level.main(null);
            this.setVisible(false);
        }
        else if(Emotion_Choser.getSelectedItem() == "Overwhelmed" || 
        Emotion_Choser.getSelectedItem() == "Clound9") //Overwhelmed Clound9
        {
            level = "hard";
            Hard_Level.main(null); 
            this.setVisible(false);
        }  
    }//GEN-LAST:event_Emotion_ChoserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mood_Selector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mood_Selector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mood_Selector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mood_Selector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mood_Selector().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Emotion_Choser;
    private javax.swing.JLabel Question_Label;
    // End of variables declaration//GEN-END:variables
}
